name: Java Selenium with TestNG - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: 'read'
  id-token: 'write'
  issues: 'write'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build the Project
      run: mvn clean install -DskipTests   
    - name: Coverage per Test Execution
      run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test
      
    - name: Upload target folder
      uses: actions/upload-artifact@v2
      with:
       name: target
       path: |
        ${{ github.workspace }}/target
        ${{ github.workspace }}/reports
        
    - name: Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: target/surefire-reports/emailable-report.html
        reporter: java-junit
        fail-on-error: true
