name: Java Selenium with TestNG - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name:  Install Google Chrome # Using shell script to install Google Chrome
      run:   |
              chmod +x ./InstallChrome.sh
              ./InstallChrome.sh 
    - name: Build with Maven
      run: mvn -B package --file pom.xml 
    - name: Test
      run: mvn -B clean test

